# Generated by Django 4.2.30 on 2026-05-18 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the category.', max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier (auto-generated from name).', max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Optional description of this category.', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this category is visible in the system.', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Trade or brand name of the medicine.', max_length=200, verbose_name='name')),
                ('generic_name', models.CharField(blank=True, help_text='Scientific or generic name (e.g., Paracetamol).', max_length=200, verbose_name='generic name')),
                ('brand', models.CharField(blank=True, help_text='Brand or manufacturer name.', max_length=200, verbose_name='brand')),
                ('barcode', models.CharField(blank=True, help_text='Unique SKU or barcode identifier.', max_length=100, null=True, unique=True, verbose_name='barcode')),
                ('unit', models.CharField(default='Pcs', help_text='Unit of measurement (e.g., Pcs, Strip, Bottle, Box).', max_length=50, verbose_name='unit')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost price per unit in BDT.', max_digits=12, verbose_name='purchase price')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Retail selling price per unit in BDT.', max_digits=12, verbose_name='selling price')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=15.0, help_text='Tax percentage applied (default 15%% BDT VAT).', max_digits=5, verbose_name='tax rate')),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Low-stock alert threshold; triggers reorder notification.', verbose_name='reorder level')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Current stock on hand (managed by inventory).', verbose_name='stock quantity')),
                ('description', models.TextField(blank=True, help_text='Optional description or usage notes.', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this medicine is active in the system.', verbose_name='is active')),
                ('image', models.ImageField(blank=True, help_text='Optional product image.', null=True, upload_to='medicines/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(blank=True, help_text='Product category for grouping.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='medicines.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['barcode'], name='medicines_m_barcode_ac4d36_idx'), models.Index(fields=['name'], name='medicines_m_name_61a774_idx')],
            },
        ),
    ]
