# Generated by Django 6.0.5 on 2026-05-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('name', 'brand', 'generic_name')},
        ),
    ]
