# Generated by Django 4.2.30 on 2026-05-18 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        ('inventory', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(help_text='Unique auto-generated invoice number.', max_length=50, unique=True, verbose_name='invoice number')),
                ('sale_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the sale was created.', verbose_name='sale date')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all line totals before discount.', max_digits=12, verbose_name='subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Flat discount amount applied to the sale.', max_digits=12, verbose_name='discount amount')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage-based discount applied to the sale.', max_digits=5, verbose_name='discount percent')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total VAT/tax across all items.', max_digits=12, verbose_name='tax amount')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Final amount payable after discount and tax.', max_digits=12, verbose_name='grand total')),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE', 'Mobile Banking'), ('MIXED', 'Mixed')], default='CASH', help_text='Method of payment used.', max_length=20, verbose_name='payment mode')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Actual amount received from the customer.', max_digits=12, verbose_name='amount paid')),
                ('change_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Change returned to the customer.', max_digits=12, verbose_name='change amount')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('HELD', 'Held'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='COMPLETED', help_text='Current state of the sale transaction.', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, help_text='Optional internal notes about this transaction.', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('cashier', models.ForeignKey(help_text='The staff member who processed this sale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='cashier')),
                ('customer', models.ForeignKey(blank=True, help_text='The customer for this sale (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units sold.', verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit at the time of sale.', max_digits=12, verbose_name='unit price')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Per-item flat discount amount.', max_digits=12, verbose_name='discount')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=15.0, help_text='Tax percentage applied at the time of sale.', max_digits=5, verbose_name='tax rate')),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Computed total: (unit_price × quantity) − discount + tax.', max_digits=12, verbose_name='line total')),
                ('batch', models.ForeignKey(blank=True, help_text='The batch from which stock was deducted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='inventory.batch', verbose_name='batch')),
                ('medicine', models.ForeignKey(help_text='The medicine being sold.', on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='medicines.medicine', verbose_name='medicine')),
                ('sale', models.ForeignKey(help_text='The parent sale transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='sale')),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sale Items',
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['invoice_no'], name='sales_sale_invoice_5ca049_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='sales_sale_sale_da_2fd927_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='sales_sale_status_532843_idx'),
        ),
    ]
