# Generated by Django 4.2.30 on 2026-05-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the customer.', max_length=200)),
                ('phone', models.CharField(help_text='Primary contact number — used as unique identifier.', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Email address (optional).', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Physical or mailing address.')),
                ('loyalty_points', models.PositiveIntegerField(default=0, help_text='Accumulated loyalty points (1 point = 1 BDT).')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this customer.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this customer is considered active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
    ]
