# Generated by Django 6.0.5 on 2026-05-24 15:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current account balance. Positive = advance (customer has credit), negative = dues (customer owes).', max_digits=12),
        ),
    ]
