# Generated by Django 4.2.30 on 2026-05-18 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the return was processed.', verbose_name='return date')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total monetary amount refunded to the customer.', max_digits=12, verbose_name='refund amount')),
                ('reason', models.TextField(help_text='Reason for the return / refund.', verbose_name='reason')),
                ('notes', models.TextField(blank=True, help_text='Optional additional notes about this return.', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('processed_by', models.ForeignKey(help_text='The staff member who processed this return.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL, verbose_name='processed by')),
                ('sale', models.ForeignKey(help_text='The original sale being returned.', on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale', verbose_name='sale')),
            ],
            options={
                'verbose_name': 'Sales Return',
                'verbose_name_plural': 'Sales Returns',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of units being returned.', verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price from the original sale.', max_digits=12, verbose_name='unit price')),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Computed total: quantity × unit_price.', max_digits=12, verbose_name='line total')),
                ('sale_item', models.ForeignKey(help_text='The original sale line item being returned.', on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='sales.saleitem', verbose_name='sale item')),
                ('sales_return', models.ForeignKey(help_text='The parent sales return transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.salesreturn', verbose_name='sales return')),
            ],
            options={
                'verbose_name': 'Sales Return Item',
                'verbose_name_plural': 'Sales Return Items',
            },
        ),
    ]
