# Generated by Django 6.0.5 on 2026-05-24 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='payee ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount.', max_digits=12, verbose_name='amount')),
                ('transaction_type', models.CharField(choices=[('ADVANCE', 'Advance / Credit'), ('PAYMENT', 'Payment Received')], default='PAYMENT', max_length=10, verbose_name='transaction type')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('MOBILE', 'Mobile Banking')], default='CASH', max_length=10, verbose_name='payment method')),
                ('reference', models.CharField(blank=True, help_text='Cheque number, transaction ID, or reference.', max_length=100, verbose_name='reference')),
                ('note', models.TextField(blank=True, help_text='Additional notes about this transaction.', verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'customers'), ('model', 'customer')), models.Q(('app_label', 'suppliers'), ('model', 'supplier')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='payee type')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='payments_pa_content_51b568_idx')],
            },
        ),
    ]
