# Generated by Django 6.0.5 on 2026-05-25 12:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0001_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DueSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_settled', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount settled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Due Settlement',
                'verbose_name_plural': 'Due Settlements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='The purchase order this payment settles (for supplier dues).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='purchases.purchaseorder', verbose_name='purchase order'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='sale',
            field=models.ForeignKey(blank=True, help_text='The sale invoice this payment settles (for customer dues).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='sales.sale', verbose_name='sale invoice'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_date',
            field=models.DateField(default=datetime.date.today, help_text='Date the transaction occurred.', verbose_name='transaction date'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_date'], name='payments_pa_transac_2ad7c5_idx'),
        ),
        migrations.AddField(
            model_name='duesettlement',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='payments.paymenttransaction', verbose_name='payment'),
        ),
        migrations.AddField(
            model_name='duesettlement',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='due_settlements', to='purchases.purchaseorder', verbose_name='purchase order'),
        ),
        migrations.AddField(
            model_name='duesettlement',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='due_settlements', to='sales.sale', verbose_name='sale invoice'),
        ),
        migrations.AddIndex(
            model_name='duesettlement',
            index=models.Index(fields=['sale'], name='payments_du_sale_id_f29c31_idx'),
        ),
        migrations.AddIndex(
            model_name='duesettlement',
            index=models.Index(fields=['purchase_order'], name='payments_du_purchas_332c48_idx'),
        ),
    ]
