# Generated by Django 4.2.30 on 2026-05-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company or supplier name.', max_length=200)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person at this supplier.', max_length=100)),
                ('phone', models.CharField(help_text='Primary contact number.', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Contact email address.', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Physical or mailing address.')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this supplier.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this supplier is considered active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
    ]
