# Generated by Django 4.2.30 on 2026-05-18 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(help_text='Batch or lot number from the supplier.', max_length=100, verbose_name='batch number')),
                ('manufacture_date', models.DateField(blank=True, help_text='Date the batch was manufactured.', null=True, verbose_name='manufacture date')),
                ('expiry_date', models.DateField(help_text='Date the batch expires.', verbose_name='expiry date')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current quantity remaining in this batch.', verbose_name='quantity')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Per-unit purchase price for this batch in BDT.', max_digits=12, verbose_name='purchase price')),
                ('purchase_order', models.CharField(blank=True, help_text='Reference PO number.', max_length=100, verbose_name='purchase order')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this batch is still active.', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('medicine', models.ForeignKey(help_text='The medicine this batch belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='medicines.medicine', verbose_name='medicine')),
                ('supplier', models.ForeignKey(blank=True, help_text='The supplier who provided this batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='suppliers.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Sale'), ('ADJ', 'Adjustment'), ('RET', 'Return')], help_text='Type of stock movement.', max_length=3, verbose_name='transaction type')),
                ('quantity', models.IntegerField(help_text='Signed quantity: positive for additions, negative for deductions.', verbose_name='quantity')),
                ('reference', models.CharField(blank=True, help_text='Human-readable reference (e.g., invoice #, PO #).', max_length=200, verbose_name='reference')),
                ('note', models.TextField(blank=True, help_text='Optional additional notes about this transaction.', verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('batch', models.ForeignKey(blank=True, help_text='The batch affected by this transaction (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ledger', to='inventory.batch', verbose_name='batch')),
                ('created_by', models.ForeignKey(help_text='User who performed the transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('medicine', models.ForeignKey(help_text='The medicine whose stock changed.', on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger', to='medicines.medicine', verbose_name='medicine')),
            ],
            options={
                'verbose_name': 'Stock Ledger',
                'verbose_name_plural': 'Stock Ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['medicine'], name='inventory_b_medicin_816c38_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['expiry_date'], name='inventory_b_expiry__96c551_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_no'], name='inventory_b_batch_n_6b3255_idx'),
        ),
    ]
