# Generated by Django 4.2.30 on 2026-05-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='MediPOS Pharmacy', help_text='Display name of the pharmacy.', max_length=200, verbose_name='shop name')),
                ('shop_address', models.TextField(blank=True, help_text='Physical address of the pharmacy.', verbose_name='shop address')),
                ('shop_phone', models.CharField(blank=True, help_text='Contact phone number for the pharmacy.', max_length=20, verbose_name='shop phone')),
                ('shop_email', models.EmailField(blank=True, help_text='Contact email address.', max_length=254, verbose_name='shop email')),
                ('shop_logo', models.ImageField(blank=True, help_text='Upload a logo for the pharmacy.', null=True, upload_to='shop/', verbose_name='shop logo')),
                ('tin_number', models.CharField(blank=True, help_text='Tax Identification Number.', max_length=50, verbose_name='TIN number')),
                ('vat_number', models.CharField(blank=True, help_text='VAT registration number.', max_length=50, verbose_name='VAT number')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=15.0, help_text='Default tax percentage applied to sales.', max_digits=5, verbose_name='default tax rate')),
                ('currency_symbol', models.CharField(default='৳', help_text='Symbol used to display prices (e.g., ৳, $, ₹).', max_length=10, verbose_name='currency symbol')),
                ('currency_code', models.CharField(default='BDT', help_text='ISO currency code (e.g., BDT, USD, INR).', max_length=5, verbose_name='currency code')),
                ('receipt_footer', models.TextField(blank=True, default='Thank you for your purchase!', help_text='Text printed at the bottom of receipts.', verbose_name='receipt footer')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='Global low-stock warning threshold.', verbose_name='low stock threshold')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Shop Settings',
                'verbose_name_plural': 'Shop Settings',
            },
        ),
    ]
