# Generated by Django 4.2.30 on 2026-05-18 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(help_text='Auto-generated unique purchase order number.', max_length=50, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now, help_text='Date the purchase order was created or sent.')),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Anticipated delivery date for this order.', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ORDERED', 'Ordered'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current status of the purchase order.', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Computed total of all line items.', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Optional internal notes about this purchase order.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update.')),
                ('created_by', models.ForeignKey(help_text='User who created this purchase order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, help_text='User who received the stock for this PO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_pos', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(help_text='The supplier this purchase order is sent to.', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units ordered.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Purchase price per unit in BDT.', max_digits=12)),
                ('batch_no', models.CharField(blank=True, help_text="Supplier's batch or lot number.", max_length=100)),
                ('expiry_date', models.DateField(blank=True, help_text="Supplier's batch expiry date.", null=True)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Computed line total (quantity × unit_price).', max_digits=12)),
                ('medicine', models.ForeignKey(help_text='The medicine being ordered.', on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='medicines.medicine')),
                ('purchase_order', models.ForeignKey(help_text='The parent purchase order.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
            },
        ),
    ]
